name: theadaptory
favicon: null
layout_spectrum: 0.5917087781708688
typography_spectrum: 0.5522993453778327
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9852019061800092
  lightness: 0.2894575013779104
  saturation: 0.9458251716569066
  rhythmicContrast: 0.14283122960478067
purpose: []
